---
# Tasks for mcs role

- name: Install base.cmd
  ansible.builtin.template:
    src: templates/base.cmd.j2
    dest: "{{ deploy_ioc_ioc_directory }}/iocBoot/base.cmd"
    mode: "0664"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"

- name: Install substitutions file
  ansible.builtin.template:
    src: templates/mcs.substitutions.j2
    dest: "{{ deploy_ioc_ioc_directory }}/db/mcs{{ ioc.model }}.substitutions"
    mode: "0664"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
