---
type: enum("powerpmac")
environment:
  ENGINEER: str(required=False)
  SYS: str()
  CONTROLLER: str()
  DEV: str()
  CT_SYS: str()
  NUM_AXES: int(min=1, max=8)
  MOVING_POLL_PERIOD: int(required=False)
  IDLE_POLL_PERIOD: int(required=False)
  CONTROLLER_IP: any(ip(), hostname())

disable_all_limits: bool(required=False)

coord_systems: list(include("coord_system"), required=False)
axes: list(include("axis"), min=1, max=8)
virtual_axes: list(include("virtual_axis"), required=False)
poll_periods: list(include("poll_period"), required=False)

---

coord_system:
  num: int()
  motion_prog: int(min=1, max=99)
  num_axes: int()

axis:
  name: str()
  num: int(min=1, max=8)
  component: str()
  desc: str()
  mres: num()
  egu: str()
  disable_limits: bool(required=False)

virtual_axis:
  name: str()
  num: int(min=1, max=8)
  cs: int()
  component: str()
  desc: str()
  mres: num()
  egu: str()
  home_plc: int(min=1, max=20)

poll_period:
  card: int(min=1, max=4)
  idle: int()
  moving: int()
  cs: bool()
