---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible lint
        language: system
        # For some reason, pre commit doesn't accept the exclude_paths from the
        # .ansible-lint file, so we pass them explicitly as an argument here
        entry: ansible-lint --offline --exclude roles/install_module/vars/*
        description: Perform ansible linting
        types: [yaml]

      - id: yamllint
        name: yaml lint
        language: system
        entry: yamllint --strict -c .yaml-lint.yml
        description: YamlLint with same config as super-linter
        types: [yaml]

      - id: ruff
        name: lint with ruff
        language: system
        entry: ruff check --force-exclude
        types: [python]
        require_serial: true

      - id: ruff-format
        name: format with ruff
        language: system
        entry: ruff format --force-exclude
        types: [python]
        require_serial: true
