---

adandor3_1e33769:
  name: ADAndor3
  version: 1e33769
  url: https://github.com/areaDetector/adandor3
  include_base_ad_config: true
  executable: andor3App
  module_deps:
    - adcore_60080dc
    - adcompvision_9750d13
    - adpluginbar_448d96b
    - ffmpeg_server_07c570f
