---

adgenicam_5d08a11:
  name: ADGenICam
  url: https://github.com/areaDetector/ADGenICam
  version: 5d08a11
  pkg_deps:
    - aravis
    - python3.11 # Required for auto-generating database and bobfiles
  include_base_ad_config: true
  module_deps:
    - adcore_60080dc
    - adcompvision_9750d13
    - adpluginbar_448d96b
    - ffmpeg_server_07c570f
