---

adkinetix_aa87406:
  name: adkinetix
  url: https://github.com/NSLS2/ADKinetix
  version: aa87406
  include_base_ad_config: true
  executable: kinetixApp
  module_deps:
    - adcore_60080dc
    - adcompvision_9750d13
    - adpluginbar_448d96b
    - ffmpeg_server_07c570f
