---

adpicam_0d86fae:
  name: ADPICam
  version: 0d86fae
  url: https://github.com/areaDetector/ADPICam.git
  include_base_ad_config: true
  executable: ADPICamApp
  module_deps:
    - adcore_60080dc
    - adcompvision_9750d13
    - adpluginbar_448d96b
    - ffmpeg_server_07c570f
