---
adpilatus_af15230:
  name: ADPilatus
  version: af15230
  url: https://github.com/areaDetector/ADPilatus
  include_base_ad_config: true
  executable: pilatusDetectorApp
  module_deps:
    - adcore_60080dc
    - adcompvision_9750d13
    - adpluginbar_448d96b
    - ffmpeg_server_07c570f
