---
nsls2em_f76d209:
  name: nsls2em
  version: f76d209
  url: https://github.com/NSLS2/nsls2em-ioc
  include_base_ad_config: true
  executable: nsls2em
  module_deps:
    - pscdrv_1ed650d
    - quadem_f5ab1e9
