---

deploy_ioc_use_ad_common: true
deploy_ioc_required_module: adaravis_a0aa4d6
deploy_ioc_template_root_path:
  "{{ deploy_ioc_required_module_path }}/iocs/aravisIOC"
deploy_ioc_as_dir_name: autosave
deploy_ioc_req_file_list:
  - name: auto_settings.req
    macros: "P=$(PREFIX)"
deploy_ioc_device_specific_env:
  PORT: "ARV1"
  QSIZE: 20
  NCHANS: 2048
  CBUFFS: 500
  MAX_THREADS: 8
  EPICS_DB_INCLUDE_PATH: "$(ADCORE)/db:$(ADGENICAM)/db:$(ADARAVIS)/db"
  NELEMENTS: 500000
