---

deploy_ioc_use_common: true
deploy_ioc_use_ad_common: true
deploy_ioc_required_module: adeiger_05e8a65
deploy_ioc_as_dir_name: autosave
deploy_ioc_template_root_path:
  "{{ deploy_ioc_required_module_path }}/iocs/eigerIOC"

deploy_ioc_device_specific_env:
  PORT: "EIG"
  QSIZE: 20
  XSIZE: 1030
  YSIZE: 1065
  NCHANS: 2048
  CBUFFS: 500
  MAX_THREADS: 8
  EPICS_DB_INCLUDE_PATH: "$(ADCORE)/db:$(ADEIGER)/db"
  NELEMENTS: 1096950
