---
deploy_ioc_use_ad_common: true
deploy_ioc_required_module: adpilatus_af15230
deploy_ioc_template_root_path:
  "{{ deploy_ioc_required_module_path }}/iocs/pilatusIOC"
deploy_ioc_req_file_list:
  - name: auto_settings.req
    macros: "P=$(PREFIX)"
deploy_ioc_device_specific_env:
  PORT: "PIL1"
  QSIZE: 20
  NCHANS: 2048
  CBUFFS: 500
  MAX_THREADS: 8
  XSIZE: 487
  YSIZE: 195
  NELEMENTS: 500000
  EPICS_DB_INCLUDE_PATH: "$(ADCORE)/db"
