---

deploy_ioc_template_root_path:
  "{{ deploy_ioc_required_module_path }}/iocs/simDetectorIOC"
deploy_ioc_required_module: adsimdetector_4b236f4
deploy_ioc_use_ad_common: true
deploy_ioc_req_file_list:
  - name: auto_settings.req
    macros: "P=$(PREFIX)"
deploy_ioc_device_specific_env:
  PORT: "SIM1"
  QSIZE: 20
  NCHANS: 2048
  CBUFFS: 500
  MAX_THREADS: 8
  XSIZE: 1024
  YSIZE: 1024
  EPICS_DB_INCLUDE_PATH: "$(ADCORE)/db"
