---

deploy_ioc_template_root_path:
  "{{ deploy_ioc_required_module_path }}iocs/uvcIOC"
deploy_ioc_required_module: aduvc_86918b6
deploy_ioc_use_ad_common: true
deploy_ioc_req_file_list:
  - name: auto_settings.req
    macros: "P=$(PREFIX)"
deploy_ioc_device_specific_env:
  CBUFFS: 500
  MAX_THREADS: 8
  NCHANS: 2048
  PORT: UVC1
  QSIZE: 20
  XSIZE: 1920
  YSIZE: 1080
  NELEMENTS: 500000
  EPICS_DB_INCLUDE_PATH: "$(ADCORE)/db"
