---

deploy_ioc_required_module: rbd9103_a835e1c
deploy_ioc_template_root_path:
  "{{ deploy_ioc_required_module_path }}/iocs/rbd9103IOC"
deploy_ioc_device_specific_env:
  SERIAL_PORT: "RBD_TTY"
  PORT: "RBD"
