---

deploy_ioc_template_root_path: "{{ deploy_ioc_required_module_path }}"
deploy_ioc_required_module: "base_stream_ioc_093e6cf"
deploy_ioc_make_autosave_files: true
deploy_ioc_device_specific_env:
  PORT: "DG645"
  PREFIX: "$(P)$(R)"
