---
deploy_ioc_use_common: true
deploy_ioc_required_module: "tpmac_44274d1"
deploy_ioc_executable: tpmac
deploy_ioc_template_root_path: "{{ deploy_ioc_required_module_path }}"
deploy_ioc_make_autosave_files: true

# Generated req files don't need macros
deploy_ioc_req_file_list:
  - name: info_positions.req
    macros: ""
  - name: info_settings.req
    macros: ""

deploy_ioc_device_specific_env:
  STREAM_PROTOCOL_PATH: "$(EPICS_BASE)/protocol:$(TPMAC)/protocol:$(TOP)/protocol:."
