---

- name: Copy base.cmd
  ansible.builtin.template:
    src: "base.cmd.j2"
    dest: "{{ deploy_ioc_ioc_directory }}/iocBoot/base.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: preserve

- name: Copy autosave req file
  ansible.builtin.template:
    src: "auto_settings.req.j2"
    dest: "{{ deploy_ioc_ioc_directory }}/auto_settings.req"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: preserve
