---

- name: Show env var to process
  ansible.builtin.debug:
    msg: "Processing {{ item }} with value {{ deploy_ioc_merged_env[item] }}"

- name: Identify macros in envvar value
  ansible.builtin.set_fact:
    deploy_ioc_macros_in_var: "{{ deploy_ioc_merged_env[item] |
                        regex_findall('\\$\\(([A-Za-z_][A-Za-z0-9_]*)\\)') }}"

- name: Show macros found in var
  ansible.builtin.debug:
    msg: "Found macros {{ deploy_ioc_macros_in_var }} in {{ item }}"

- name: Assign temporary replacement envvar
  ansible.builtin.set_fact:
    deploy_ioc_replaced_macros: "{{ deploy_ioc_merged_env[item] }}"

- name: Replace macros in envvar
  ansible.builtin.include_tasks: replace-macros.yml
  loop: "{{ deploy_ioc_macros_in_var }}"
  loop_control:
    loop_var: "deploy_ioc_macro_in_var"

- name: Replace value of var in merged env with temp
  ansible.builtin.set_fact:
    deploy_ioc_merged_env:
      "{{ deploy_ioc_merged_env | combine(deploy_ioc_updated_macro) }}"
  vars:
    deploy_ioc_updated_macro:
      "{ '{{ item }}': '{{ deploy_ioc_replaced_macros }}' }"


# We need to recursively do this again and again until no macros remain
- name: Find envvars that use macros
  ansible.builtin.set_fact:
    deploy_ioc_envvars_with_macros: "{{ deploy_ioc_merged_env | dict2items |
                                      selectattr('value', 'search', '\\$\\(') |
                                      map(attribute='key') |
                                      list }}"

- name: Expand all macros in value of {{ item }}
  ansible.builtin.include_tasks: process-env.yml
  with_items: "{{ deploy_ioc_envvars_with_macros }}"
